title: DevKev
description: I'm Kevin, a Ruby and Clojure web developer based in Leipzig. I share insightful blog posts, articles, and conference talks that I find valuable and worth reading.
url: # devkev.de
signoff: Kevin

links:
  - name: Blog
    url: /
  - name: About
    url: /about

permalink: /blog/:title
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - CNAME
